/*
 * dbRemover.java
 *
 * Created on November 7, 2008, 2:37 PM
 */

import java.io.*;

/**
 *
 * @author  Ankit Singh
 */
public class dbRemover extends javax.swing.JFrame
{
    static File f=null;
    float s=0;
    int c=0;

    /** Creates new form dbRemover */
    public dbRemover()
    {
        initComponents();
        changeTheLookAndFeel( 3 );
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        javax.swing.JFileChooser fc=new javax.swing.JFileChooser();
        fc.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY );
        int r=fc.showDialog(this,"Select folder");
        f = fc.getSelectedFile();
        if(r==javax.swing.JFileChooser.CANCEL_OPTION || ( f.getName().equals( "" ) ))
            f=null;
        else if(f!=null)
            jButton1.setEnabled(true);
    }

    private void changeTheLookAndFeel( int value )
   {
        javax.swing.UIManager.LookAndFeelInfo looks[];
        looks = javax.swing.UIManager.getInstalledLookAndFeels();
      try // change look and feel
      {
         // set look and feel for this application
         javax.swing.UIManager.setLookAndFeel( looks[ value ].getClassName() );

         // update components in this application
         javax.swing.SwingUtilities.updateComponentTreeUI( this );
      } // end try
      catch ( Exception exception ) 
      {
          javax.swing.JOptionPane.showMessageDialog(this,"L&F error.","Internal error",javax.swing.JOptionPane.ERROR_MESSAGE);
//         exception.printStackTrace();
      } // end catch
   } // end method changeTheLookAndFeel
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 13));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Scan");
        jButton1.setToolTipText("Scan for thumbs.db & PCM.db files");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("RemoveAll");
        jButton2.setToolTipText("Remove al thumbs.db & PCM.db files");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton1)
                .addGap(109, 109, 109)
                .addComponent(jButton2)
                .addContainerGap(61, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    jTextArea1.append("\n    FILE    SIZE(bytes)\n");
    File[] fi=f.getAbsoluteFile().listFiles();
        for (int i = 0; i < fi.length; i++)
        {
            if(fi[i].isDirectory())
            {
                Size(fi[i]);
            }
            else if(fi[i].isFile() && ( fi[i].getName().equals("Thumbs.db") || fi[i].getName().equals("PCM.db") ) )
            {
                jTextArea1.append(++c+">"+fi[i].getName()+"   "+fi[i].length()+"\n");
                s=s+fi[i].length();
            }
        }
    jTextArea1.append("\n"+"-----------------------"+"\n");
    if(s<1024)
    {
        jTextArea1.append("Total size = "+s+" bytes");
    }
    else if(s>=1024 && s<1048576)
    {
        jTextArea1.append("Total size = "+s/1024+" KB");
    }
    else if(s>1048576)
    {
        jTextArea1.append("Total size = "+s/1048576+" MB");
    }
    jTextArea1.append("\n"+"-----------------------"+"\n");
    jButton2.setEnabled(true);
    c=0;
    s=0;
}                                        

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    jTextArea1.append("\n"+"Deleting all 'Thumbs.db' & 'PCM.db' files..."+"\n");
    c=0;
    File[] fi=f.getAbsoluteFile().listFiles();
        for (int i = 0; i < fi.length; i++)
        {
            if(fi[i].isDirectory())
            {
                Del(fi[i]);
            }
            else if(fi[i].isFile() && ( fi[i].getName().equals("Thumbs.db") || fi[i].getName().equals("PCM.db") ) )
            {
                if( fi[i].delete()==true )
                {
                    jTextArea1.append( (++c) +">"+ fi[i].getName()+" ...Deleted"+"\n");
                }
            }
        }
    jTextArea1.append("All 'Thumbs.db' & 'PCM.db' files deleted."+"\n\n");
    s=0;
}                                        

    public void Size(java.io.File f)
    {
        java.io.File fi[]=f.listFiles();
        for (int i = 0; i < fi.length; i++)
        {
            if(fi[i].isDirectory())
            {
                Size(fi[i]);
            }
            else if(fi[i].isFile() && ( fi[i].getName().equals("Thumbs.db") || fi[i].getName().equals("PCM.db") ) )
            {
                jTextArea1.append(++c+">"+fi[i].getName()+"   "+fi[i].length()+"\n");
                s=s+fi[i].length();
            }
        }
    }

    public void Del(java.io.File f)
    {
        java.io.File fi[]=f.listFiles();
        for (int i = 0; i < fi.length; i++)
        {
            if(fi[i].isDirectory())
            {
                Del(fi[i]);
            }
            else if(fi[i].isFile() && ( fi[i].getName().equals("Thumbs.db") || fi[i].getName().equals("PCM.db") ) )
            {
              if( fi[i].delete()==true )
              {
                  jTextArea1.append( (++c) +">"+ fi[i].getName()+"...Deleted"+"\n");
              }
            }
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dbRemover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   

}
