
import java.io.File;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileLister2.java
 *
 * Created on Jun 8, 2009, 3:28:18 PM
 */

/**
 *
 * @author Ankit Singh
 */
public class FileLister extends javax.swing.JFrame {

    static java.io.File f[]=null;

    /** Creates new form FileLister2 */
    public FileLister()
    {
        initComponents();
        changeTheLookAndFeel( 3 );
        javax.swing.JFileChooser fc=new javax.swing.JFileChooser();
        fc.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY );
        fc.setMultiSelectionEnabled(true);
        int r=fc.showDialog(this,"Select folder");
        f = fc.getSelectedFiles();
        if(r==javax.swing.JFileChooser.CANCEL_OPTION || ( f.length==0 ))
            f=null;
        else if(f!=null)
        {
            for (int i = 0; i < f.length; i++)
            {
                jTextArea1.append( f[i].getName().toUpperCase()+"\n\n" );
                Size(f[i]);
                jTextArea1.append("\n************************END_OF_LIST************************\n\n");
            }
        }
//            jButton1.setEnabled(true);
    }

    private void changeTheLookAndFeel( int value )
   {
        javax.swing.UIManager.LookAndFeelInfo looks[];
        looks = javax.swing.UIManager.getInstalledLookAndFeels();
      try // change look and feel
      {
         // set look and feel for this application
         javax.swing.UIManager.setLookAndFeel( looks[ value ].getClassName() );

         // update components in this application
         javax.swing.SwingUtilities.updateComponentTreeUI( this );
      } // end try
      catch ( Exception exception )
      {
          javax.swing.JOptionPane.showMessageDialog(this,"L&F error.","Internal error",javax.swing.JOptionPane.ERROR_MESSAGE);
//         exception.printStackTrace();
      } // end catch
   } // end method changeTheLookAndFeel

    void Size(java.io.File f)
    {
        int c=0;
//        long s=0;
        java.io.File fi[]=f.listFiles();
        for (int i = 0; i < fi.length; i++)
        {
            if(fi[i].isDirectory())
            {
                jTextArea1.append(fi[i].getPath()+"  - FOLDER\n");
                Size(fi[i]);
            }
            else if( fi[i].isFile() && fi[i].length()>1048576)
            {
                jTextArea1.append(++c+">"+fi[i].getName()+"   "+fi[i].length()/1048576+" MB\n");
//                s=s+fi[i].length();
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FileLister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
